export const ROUTES = {
  HOME: '/',
  LOGIN: '/login',
  CADASTRO: '/cadastro',
  CATALOGO: '/catalogo',
  CRIAR_FICHA: '/ficha/criar',
  DETALHES_PRODUTO: '/ficha/detalhes',
  DETALHES_PEDIDO: '/ficha/pedido',
  CONFIRMACAO: '/ficha/confirmacao',
  MEUS_PEDIDOS: '/pedidos',
  MEU_PERFIL: '/perfil',
  ADMIN_KANBAN: '/admin/kanban',
  ADMIN_FICHAS: '/admin/fichas',
  ADMIN_CUSTOS: '/admin/custos',
  DASHBOARD: '/cliente',
}
