version: '3.8'
services:
  db:
    image: postgres:16-alpine
    container_name: postgres-seriestudio
    environment:
      POSTGRES_DB: seriestudio
      POSTGRES_USER: seriestudio
      POSTGRES_PASSWORD: seriestudio
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  backend:
    build: .
    container_name: backend-seriestudio
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/seriestudio
      SPRING_DATASOURCE_USERNAME: seriestudio
      SPRING_DATASOURCE_PASSWORD: seriestudio
    ports:
      - "8080:8080"
    depends_on:
      - db

volumes:
  pgdata:
